SELECT COUNT(*)
FROM (
         SELECT DISTINCT NAME
         FROM ANIMAL_INS
         WHERE NAME IS NOT NULL
     ) AS distinct_names;


SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;