SELECT
    C.CAR_ID,
    CASE
        WHEN R.CAR_ID IS NOT NULL THEN '대여중'
        ELSE '대여 가능'
        END AS AVAILABILITY
FROM (
         SELECT DISTINCT CAR_ID
         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     ) C
         LEFT JOIN (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
) R
                   ON C.CAR_ID = R.CAR_ID
ORDER BY C.CAR_ID DESC;