SELECT FH.FLAVOR
FROM FIRST_HALF FH
         LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) JY
                   ON FH.FLAVOR = JY.FLAVOR
ORDER BY FH.TOTAL_ORDER + IFNULL(JY.TOTAL_ORDER, 0) DESC
LIMIT 3;